### ISSUE TITLE
F-Droid Inclusion?

### ISSUE THREAD

**Issue by TPS** [Keidan/HexViewer#1]
@Keidan Would you support an [RFP](https://gitlab.com/fdroid/rfp) @ [F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-1)?  [IfF](https://en.m.wikipedia.org/wiki/Iff) so, [I'd happily open 1 up](https://gitlab.com/fdroid/rfp/issues/new).

RFP's @ https://gitlab.com/fdroid/rfp/-/issues/1644

**Comment by Keidan** [comment]
Hello,

Sorry for the late response.
I don't really know F-Droid and I don't know what it implies in terms of maintainability and code availability for this project.

**Comment by TPS** [comment]
@IzzySoft I seem to remember that you've an extensive prepared response to @Keidan's questions re: what's F-droid & its benefits to developers, but I can't find to link to such (&, _of course_, I wouldn't feel comfortable to copy/paste it, either).

**Comment by IzzySoft** [comment]
@TPS you can simply link it :laughing:

@Keidan F-Droid is a place for free/libre open source Android apps – which doesn't kick your app out for donation links (or other crazy reasons like not using their own payment system or offering another one as alternative), spy on its users, monetarize their data without a real "approvement", etc. You'll always reach real people there (instead of getting robot responses with unhelpful standard text templates). It's especially loved by the privacy-focused folks.

To read more about it, you can take a look at the official website ([F-Droid.org](https://f-droid.org/), or get a quick overview reading [my 3 articles](https://android.izzysoft.de/articles/named/fdroid-intro) (which are what I meant @TPS can link to any time). If you've got specific questions, reach out to us – you can e.g. always find us on IRC (channels `#fdroid` and `#fdroid-dev` at Freenode).

**Comment by TPS** [comment]
@Keidan So, _are_ you interested in having this in F-droid? _(I hope I gave you enough time to ruminate! 🙇🏾‍♂️)_

**Comment by Keidan** [comment]
Hello, 

Haha of course, I had time to ruminate :D
I'm torn between accepting it and the fact that I don't really have the time to maintain the application if there are problems with it.

**Comment by Keidan** [comment]
So, if it's not a problem, go

**Comment by TPS** [comment]
Maybe baby steps?

_(@IzzySoft Would you be willing to host on your repo, given @Keidan provides some APKs?  Or, do you know whether it's possible to release an app on F-Droid as_ only _beta/unstable updates?)_

Either of these would minimize the number of users, which would give you the experience to see if you'd wish to handle a wider release.  Also, it's usually several _months_ from initial F-Droid RFP to first publishing on the main repository, so there'll be time from the initial consent, anyway.

**Comment by IzzySoft** [comment]
@Keidan quoting your Readme:

> This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.

We try to not cause you too much headache. So I guess @TPS will prepare [Fastlane structures](https://gitlab.com/snippets/1895688) for you and provide them via a PR you just have to merge, and then we would ask you to [tag your releases](https://github.com/Keidan/HexViewer/releases) (a way of "signaling" F-Droid which versions it should build). Just remember to always increase `versionCode` with new releases, as that's what Android tells them apart.

Thanks!

**Comment by Keidan** [comment]
Thank you both.

Don't worry, as soon as you give it to me I'll make the release.
Is there a format to respect for the content of the release texts?

For versions, generally, I always increment the `versionCode` and `versionName` fields.

**Comment by TPS** [comment]
> So I guess @TPS will prepare [Fastlane structures](https://gitlab.com/snippets/1895688) for you

@IzzySoft Is that mostly what I'm doing when I follow the RFP template?  I've never actually made the full Fastlane structures' files _myself_ to PR anyplace.

**Comment by fossdd** [comment]
Okay, i've replied at your [RFP](https://gitlab.com/fdroid/rfp/-/issues/1644#note_508435222).

At the link @IzzySoft linked (https://gitlab.com/snippets/1895688) are the notes for fastlane. You only have to create some folders  and place the files with the content inside.

**Comment by TPS** [comment]
@fossdd My phone glitched & published the RFP prematurely, & so it's incomplete.  It's also not letting me back into it to edit or see your reply , so I've got to get to my laptop for any of the above.  _(So_ aggravating _that GitLab hasn't an official Android app, like GitHub has!)_

**Comment by TPS** [comment]
I've completed the [RFP](https://gitlab.com/fdroid/rfp/-/issues/1644), so it's complete for perusal now.

@Keidan I'm going to study to prepare the Fastlane structure, but I need the _tiniest_ help re: what you prefer for the various media as noted in the FastLane snippet:
```
            │   ├── video.txt (URL to a video introducing the app)
            │   ├── images
            │   │   ├── icon.png            (app icon; useful e.g. for "service apps" containing none)
            │   │   ├── featureGraphic.png  (promo banner, shown on top of the app desc in F-Droid client; landscape) ³
            │   │   ├── promoGraphic.png    (same, smallscreen size?)
            │   │   ├── tvBanner.png        (same, TV-screen size?)
            │   │   ├── phoneScreenshots    ²
            │   │   │   ├── 1.png
            │   │   │   ├── 2.png
            │   │   │   ...
            │   │   ├── sevenInchScreenshots/
            │   │   ├── tenInchScreenshots/
            │   │   ├── tvScreenshots/
            │   │   └── wearScreenshots/
```
I found https://github.com/Keidan/HexViewer/tree/master/app/src/main/res (which has some icons).  Is there a better place to find more or would you be willing to make such as you prefer?

**Comment by Keidan** [comment]
video.txt -> I don't have one and when I think about what the application does, I don't find this part relevant.
icon.png -> the icon ic_launcher.png (mipmap-xxxx directories).
featureGraphic.png -> Is it mandatory?
promoGraphic.png -> Is it mandatory?
tvBanner.png -> Is it mandatory?
phoneScreenshots -> I would have to do

I'm really uncomfortable with anything to do with publishing/promoting applications. This is also one of the reasons why I usually only broadcast on github :D

**Comment by fossdd** [comment]
Of course aren't all files essentisl. For the initial setup only `short_description.txt` and `full_description.txt` required. Such things like screenshots are recommended, but not needed.

**Comment by ClockGen** [comment]
Please remove signing config from app/build.gradle (since f-droid buildserver needs unsigned APKs), right now it builds and signs the app with a public key that anyone can access (since key alias and password are just written in build.gradle).

**Comment by IzzySoft** [comment]
As @fossdd stated: just start with the essentials. You can always build on that later:

* **mandatory:** short and full description
* **strongly recommended:** phoneScreenshots (plus, if your app uses XML icons only, an icon)
* **really nice to have:** featureGraphic, per-release changelogs

Everything else is "icing on the cake". Guess my snippet even indicated that (I thought I had made sure of that). Completely useless: tvScreenshots if the app doesn't even run on AndroidTV, tvBanner (AFAIK is not even used). Just because Fastlane offers some feature doesn't mean it's mandatory – or in specific cases even useful at all :wink:

**Comment by Keidan** [comment]
I removed the signature, added screenshots (plus other changes in my code).

Let me know if you want me to do other things

**Comment by ClockGen** [comment]
I've opened a MR with app metadata, however it's still marked as WIP since there's still no correct fastlane structure in this repo https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8377

**Comment by Keidan** [comment]
Ha ok, that's the part I didn't quite understand.
So I have to add the fastlane structure at the root of this project?
In the release I'm going to create (after adding fastlane) should I include the apk (I think not but I prefer to be sure)?

**Comment by fossdd** [comment]
You never have to include somewhere the builded APK. We build all from source.

Your fastlane structures looks good. 👍🏿 

But we still want to use tags for checking out. You create a [GitHub release](https://github.com/Keidan/HexViewer/releases) for every new version.

Then we can also update by looking for new tags. Instead of everytime checking the build.gradle.

**Comment by Keidan** [comment]
Ok, ok, I created the releases.

I want to thank you all for your time.

**Comment by IzzySoft** [comment]
> So I have to add the fastlane structure at the root of this project?

Yes, it's intended to be global. Note the 3rd level of its structure: `fastlane/metadata/android`? 1st level (`fastlane`) is the "container", if you use them your fastlane binaries go there as well. 2nd level (`metadata`)  is for project metadata; AFAIK it only holds sub-directories for specific "targets". Now the 3rd level specifies the target: `android`, `ios` etc.

So as it's global and intended to cover all "targets", it must be "at the root".
