### ISSUE TITLE
FEATURE REQUEST: User customizations

### ISSUE THREAD

**Issue by ChiefMikeK** [Keidan/HexViewer#11]
Some apps such as [Markor: Text editor](https://github.com/gsantner/markor ) are capable of inserting user script on preloading of a file display.

**Background** 
- Android screens are usually small and I sometimes find it difficult to click on the line that I want (big fingers) also reading strings since the app doesn't have pinch to zoom on my Huawei Mediapad T8 (andriod 10 AOSP)
- Most users of a program such as this should be able understand the use of css or java script.   
### √ Minimally allow these **`CSS`** and/or **`JS`** properties to be added by user's + allow toggle on/off setting

- word-spacing ~	_Increases or decreases the space between **words** in a text_
- letter-spacing ~	_Increases or decreases the space between **characters** in a text_
- font 	~ _A shorthand property for the font-style, font-variant, font-weight, **font-size/line-height**, and the **font-family** properties_
- color ~ _Foreground ie. the text color_
- background-color ~ _the pages color_  
### ExampleCODE to squeeze or stretch hexWords "`a0 00 00 fa`" by 2px  
    ​<style>
      font: "bold 12px/30px mono,sans-serif";
      word-spacing: "-2px";
    </style>

----

    <script>
    function myFmyDon() {
      document.getElementById("myDISPLAY").style.wordSpacing = "-2px";
    }
    </script>

---
:neckbeard:

**Comment by Keidan** [comment]
Hello,

Thank you for your interest and proposal.

### Pinch to zoom :
I thought about it, but the ratio between the gain and the development constraints is not balanced, that's why I didn't implement this solution.

### JS/CSS :
The use of these technologies requires the use of a WebView (I don't see any other component to do it).
But the WebView has very poor performance and takes an exponential amount of time to load depending on the number of items I add to it.

I'll still modify the code to allow customization of some fields via parameters :
*   Font size.
*   Spacing between lines
*   Perhaps others.

However, the following fields will not be editable:
*   Font family
*   Text color
*   Background color

**Comment by ChiefMikeK** [comment]
#Thanks looking forward to it :neckbeard:
