### ISSUE TITLE
Add notification when memory is low

### ISSUE THREAD

**Issue by Keidan** [Keidan/HexViewer#127]
Added a notification and cancellation of the opening if the memory reserved for the application is too low.
The proposed solution is not super reliable but it is better than a crash...

I will add the following texts:
"Unable to execute the command because there's not enough memory for this application"
_called when low memory is detected_

"Memory threshold"
_menu title (in settings)_
"Threshold value for the memory limit before the opening of a file is aborted."
_menu description(in settings)_

@OmlineEditor & @sr093906 Can you please give me the translation?
Thank you in advance.

**Comment by OmlineEditor** [comment]
"Unable to execute the command because there's not enough memory for this application":
Не удалось выполнить команду, потому что для этого приложения недостаточно памяти

"Memory threshold":
Порог памяти

"Threshold value for the memory limit before the opening of a file is aborted":
Пороговое значение для ограничения памяти до прерывания открытия файла


I understand what you wrote about, but other users who do not understand programming well will not be able to properly understand the meaning of the text. It's hard for me to come up with a more understandable description and meaning yet. I think we need to release the program and then, if anything, we will change the text. we need to see in reality how the new function will work

**Comment by sr093906** [comment]
"Unable to execute the command because there's not enough memory for this application"：无法执行命令，因可供此程序使用的内存不足。

"Memory threshold"：内存阈值

"Threshold value for the memory limit before the opening of a file is aborted."：系统内存用量达到此值后，打开文件操作将被终止。

**Comment by Keidan** [comment]
Thank you very much
