### ISSUE TITLE
strange behavior when opening a file

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#161]
there are two ways to open a file using a file manager

1) select documents or photos from the menu in the list and open the file from this menu. (ready built-in menu)
2) select the carrier phone, go to the documents folder or the DCIM folder and open the file from there. (I use my hands to tell the path by moving through the folders)

if I open it, I use the first option (ready built-in menu) the error is shown that the file is read-only.
if you open the same file using the second method then there are no problems

![1](https://user-images.githubusercontent.com/13348933/146403667-fe94100c-73aa-4efc-8f5c-c16c7055a920.jpg)

**Comment by OmlineEditor** [comment]
the standard built-in android 9 file manager.
the first option opens the folder immediately.
the second option is to specify the path to the folder


![111](https://user-images.githubusercontent.com/13348933/146406608-fd04044f-9e87-47ca-b7df-0628c824494a.jpg)

**Comment by Keidan** [comment]
Okay, I understand better.
The first one will generate URIs that don't match anything on the smartphone, I seem to have seen people on stackoverflow talking about this. I'll see if I can base it on what they did...

**Comment by Keidan** [comment]
I don't have the same error as you with the emulator, but I think the problem is similar. It is due to a regression introduced when fixing the file corruption, where I was opening the file in read and write mode.
In your case, it should be opened in read-only mode, which makes sense because in this mode (opening from outside), I will only read the file and nothing else...
