### ISSUE TITLE
Errorr

### ISSUE THREAD

**Issue by QPLAYid** [Keidan/HexViewer#250]
![Screenshot_2023-02-24-20-23-19-335_fr ralala hexviewer](https://user-images.githubusercontent.com/102419809/221167964-caa14d4f-f3c6-4977-96c3-4a8f9bcbb7da.jpg)

**Comment by Keidan** [comment]
Thanks for your feedback,

Can you give me the procedure that led to this error?

**Comment by Keidan** [comment]
The full message is as follows:
"Unable to execute the command because there's not enough memory for this app"

I'll make the error messages appear in full for all devices.

However, I can't do anything about the origin of the error. If the application encounters this case, it is because Android cannot give more memory to process the file.

**Comment by QPLAYid** [comment]
I open file sizs 65mb but i used hex editor anothe app is fine but i use you app i get error

**Comment by QPLAYid** [comment]
I open file lib.so

**Comment by Keidan** [comment]
Comme indiqué dans le fichier readme, cette application ne peut pas ouvrir les fichiers qui dépassent ~20Mb.
That's why I added the partial opening mode

**Comment by QPLAYid** [comment]
Oh oke
